### ISSUE TITLE
Operabot

### ISSUE THREAD

**Issue by missaugustina** [missaugustina/allegory_of_the_ai#1]
train a chatbot/sentiment analysis thing using opera musical scores and libretto and see what happens (I expect this to be functionally useless but possibly hilarious)

**Comment by jimspohrer** [comment]
I am reminded of ____________  (Schank's Dynamic Memory book, fill in the blank test):

Gilbert and Sullivan reminding: https://en.wikipedia.org/wiki/Gilbert_and_Sullivan

**Comment by missaugustina** [comment]
Close this issue once it has been converted to a Milestone and tasked out.

**Comment by missaugustina** [comment]
This issue was moved to allegory-of-the-ai/brainstorming#1
